import re
from pydantic import BaseModel, Field
from typing import Optional, Dict, Any
from pydantic import Field, model_validator

import uuid

class IdentifiedModel(BaseModel):
    # The ID is optional at first, it will be generated by the validator
    id: Optional[str] = Field(None, description="UUID unique ou hash identifiant")

    @model_validator(mode="before")
    @classmethod
    def auto_generate_id(cls, data: Any) -> Any:
        if isinstance(data, dict) and "id" not in data: #We generate an uuid for encyclopedia entries and relationships
            data["id"] = str(uuid.uuid4())
        return data

class DescriptiveModel(IdentifiedModel):
    title: str = Field(..., description="Easy-readable name, proper name")
    slug: str = Field(..., description="Slugified name for comparisons, intern process")

    @model_validator(mode="after")
    def sync_slug(self) -> "DescriptiveModel":
        if not self.slug:
            self.slug = slugify_entity(self.title)
        return self

def slugify_entity(value: str) -> str:
    """
    Standardizes entity titles for graph consistency:
    'Maymuna bint al-Harith' -> 'MAYMUNA_BINT_AL_HARITH'
    """
    if not value:
        return ""
    # 1. Convert to Uppercase
    value = value.upper()
    # 2. Remove special characters (apostrophes, etc.)
    value = re.sub(r"[^A-Z0-9\s_-]", "", value)
    # 3. Replace spaces and hyphens with underscores
    value = re.sub(r"[\s-]+", "_", value)
    # 4. Strip leading/trailing underscores
    return value.strip("_")